server:
  port: 8801

#配置中心
spring:
  application:
    name: sso-config
  cloud:
    config:
      server:
        git:
          uri: http://192.168.110.162/sso-config/storage.git
          username: fuqingqing
          password: ck123456
          search-paths: /{application}
  security:
    user:
      name: potato
      password: tomato